In [4]:
# Representation of quantum states
import qutip as qt

# Define the ket states |0⟩ and |1⟩
ket_0 = qt.basis(2, 0)
ket_1 = qt.basis(2, 1)

In [5]:
ket_0

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

In [6]:
ket_1

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]

In [8]:
#Vector and linear combination of vector spaces

import numpy as np
# Define scalar coefficients
alpha = 0.6
beta = 0.8

# Scalar multiplication
alpha_ket_0 = alpha * ket_0
beta_ket_1 = beta * ket_1

# Vector addition (Linear combination)
linear_combination = alpha_ket_0 + beta_ket_1

In [9]:
alpha_ket_0

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.6]
 [0. ]]

In [10]:
beta_ket_1

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0. ]
 [0.8]]

In [11]:
linear_combination

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.6]
 [0.8]]

In [12]:
# Normalize the linear combination to ensure it's a valid quantum state
normalized_combination = linear_combination.unit()

print("\nNormalized Linear Combination:")
print(normalized_combination)

# Verify the normalization
norm = normalized_combination.norm()
print(f"\nNorm of the normalized combination: {norm}")


Normalized Linear Combination:
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.6]
 [0.8]]

Norm of the normalized combination: 1.0


In [17]:
# Inner product
inner_product = ket_0.overlap(ket_1)
print(inner_product)

0j


In [18]:
# Orthonormality 

ket_0 = qt.basis(2, 0)
ket_1 = qt.basis(2, 1)

# Compute the inner products
inner_product_0_1 = ket_0.overlap(ket_1)  # ⟨0|1⟩
inner_product_0_0 = ket_0.overlap(ket_0)  # ⟨0|0⟩
inner_product_1_1 = ket_1.overlap(ket_1)  # ⟨1|1⟩

print("\nInner Product ⟨0|1⟩ (Orthogonality Check):")
print(inner_product_0_1)

print("\nInner Product ⟨0|0⟩ (Normalization Check for |0⟩):")
print(inner_product_0_0)

print("\nInner Product ⟨1|1⟩ (Normalization Check for |1⟩):")
print(inner_product_1_1)

# Check if the vectors are orthonormal
are_orthonormal = (inner_product_0_1 == 0) and (inner_product_0_0 == 1) and (inner_product_1_1 == 1)

print("\nAre the vectors orthonormal?")
print(are_orthonormal)



Inner Product ⟨0|1⟩ (Orthogonality Check):
0j

Inner Product ⟨0|0⟩ (Normalization Check for |0⟩):
(1+0j)

Inner Product ⟨1|1⟩ (Normalization Check for |1⟩):
(1+0j)

Are the vectors orthonormal?
True
